### ISSUE TITLE
'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)

### ISSUE THREAD

**Issue by KraetSpg** [st1vms/unofficial-claude-api#26]
I get this issue when calling any of the clients methods. 
'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)

**Comment by st1vms** [comment]
@KraetSpg Thanks for reaching out.

Unfortunately, I can't reproduce the issue on my end.

I may need to know the exact method throwing you this error, and the context of operation.

**Comment by st1vms** [comment]
Closing this as not planned.

**Comment by KraetSpg** [comment]
Thanks, it was a random char in my cookie, I just deleted it and it worked.
